### PR TITLE
Adding nginx config with compression and short term caching

### PR DESCRIPTION
**Pull request by epacke**
Adding a simple nginx config to use in the containerized version. It supports compression and microcaching (30s).
I've prepared a guide on how to get started with the report and will publish it once this is merged.

### CODE REVIEW

**Comment by timriker** [comment]
This config is for having nginx do the compression. If we're going to compress on the fly, might as well use an F5 with an HTTP Compression profile.
The change I'd like to see is to pre-compress the files in the target directory. See my comments in #175

**Comment by epacke** [comment]
Would it be ok to handle that in a separate branch? This is functional and I'd rather not add more features now while we test docker.

**Comment by timriker** [comment]
Sure. I'm still testing things. I'd like to find a native PowerShell way to compress the files. Not working yet. I updated my timriker branch to master, and I'll work on this there. All I've done so far is add to .gitignore. :)

**Comment by epacke** [comment]
I'll interpret this as an approval then an will merge the PR. Normally I'd avoid doing it without approval but I figured since this is not affecting existing deployments and you probably forgot to click on the button it could be deemed ok. :)

**Pull request merged**
