### PR TITLE
Using string builder

### PR DESCRIPTION
**Pull request by epacke**

### CODE REVIEW

**Comment by epacke** [comment]
@timriker Does this look OK to you?

**Comment by timriker** [comment]
I hope to test this this afternoon and compare the output and performance. This is my last day in the office before heading out on vacation, so I'll try to make it a priority. Code looks good. I'll test shortly.

**Comment by epacke** [comment]
I will change the method to the one you suggested in the PR and test it tomorrow as well.

**Comment by timriker** [comment]
The difference is pretty small. StringBuilder seems to be the recommended interface. Let me test it and get back to you.

**Comment by epacke** [comment]
Actually, using the test that you provided it looks to be more than twice as fast. It's not as "pretty" as string builder though and both should be a great improvement. String builder shaved off 7 minutes from our report (15 minutes down to 8) so the results are already really good. 

The report used to run in slightly under an hour a year or so ago, but since then I've added hash tables, pulling recursive configuration, and changed the method that the files are written to disk. Did not even consider this part though so it was a great addition.

**Comment by timriker** [comment]
Works great! Went from 88 minutes down to 4-5 minutes. Awesome.
Line coloring messes up with the:
'@)
I think this is valid syntax and the vim powershell syntax plugin is getting it wrong. Visual Studio Code gets it right, and the script runs correctly. I'll push on the vim syntax maintainer. :)

**Comment by epacke** [comment]
Wow, that's really good! I'll merge and release then.

**Pull request merged**
