### PR TITLE
Feature/html

### PR DESCRIPTION
**Pull request by timriker**
I hope this set is small enough to review. The first section has whitespace, but the rest are actual code changes.

* html syntax (title, meta, remove NOWRAP, ";" typo, extra backslash, lang)
* alt= references on images
* change $i to $asm on asm look to stop overwriting $i
* trim() all lines on output when not Verbose

All pretty minor changes and all to the main script. Output looks much better on W3C validator.

### CODE REVIEW

**Comment by epacke** [comment]
Hi Tim!
How about having a short meeting one of these days? Would feel good to e-meet. :) Will test this soon and get back to you.

/Patrik

**Comment by timriker** [comment]
Life is pretty busy for me at the moment. I'll be offline and out of town for a week or so.
There are more files under Move.... that could get whitespace cleaned. I'm testing different options to avoid the string concatenation slowness now. Here's an example:
https://pastebin.com/3486anmq
Keep in mind that for me the script is probably doing millions of contatinations. My last run took 88 minutes as I posted earlier. Almost all of that is generating the html.
Ideally the interface would load all the data in json, and then render the visible entries in a table only. Also it would be nice if the UI was visible and the "pace" bar was only over where the table will end up. It takes a couple minutes for the page to load. I'll time that more precisely.

**Comment by epacke** [comment]
I will try the string builder today. It was an excellent idea.

**Comment by timriker** [comment]
The last example wins by speed. That one uses:
System.Collections.Generic.List[System.String]
Thoughts on that?

**Comment by epacke** [comment]
Darn, I missed that one. Lemme get back to you.

**Pull request merged**
