### PR TITLE
Linting and token extension

### PR DESCRIPTION
**Pull request by epacke**
Functional changes
* Patching the token to last for 120 minutes instead of 20 (I ran out of time on one of my device groups)
* Using a session variable instead of manual headers

Linting, prettifying, optimizing and removing redundant code:
* Caching jQuery selectors
* Use of let instead of var
* Removing unused variables
* Changing double quotes to single
* 2 x space for tab instead of 4x
* Declaring undeclared variables
* Ran prettier once
* Added eslint config file and automatic linting for bigipreport.js (check the actions tab)

### CODE REVIEW

**Comment by epacke** [comment]
Tip when reviewing. I think you already know but just in case:

image

**Comment by timriker** [comment]
I prefer ttbs over stroustrup so we have:
} else {
instead of:
}
else {

**Comment by epacke** [comment]
> I prefer ttbs over stroustrup so we have:
> } else {
> instead of:
> }
> else {
> See https://eslint.org/docs/rules/brace-style

Soooo glad we agree on this one. I added `"brace-style": ["error", "1tbs"],` to the eslint config.

**Comment by timriker** [comment]
Should have put the comment here.
The .ps1 has:
}
else {
formatting. Can we fix that to "} else {" for else, elseif, etc?

**Comment by epacke** [comment]
Absolutely, I did not see that change. I can fix linting for the ps script too. :)

**Comment by epacke** [comment]
I did not find any quick way to do linting so I'll put a mind note to do this later. But the style is restored.

**Comment by timriker** [comment]
Do we want package-lock.json in the repository? I would assume we don't. So far the packages are only used for validation, right? So the end user won't need them, and our development environments may differ.

**Comment by epacke** [comment]
I'm planning to add unit-tests for the scripts later and package-lock.json prevents keeps things realtively consistent and prevent bugs. I've done a fair share of pipelines lately and the gurus say to lock the dependencies. :)

**Review by timriker — APPROVED** [review]
Looks good to me. There's a lot to test. The 'const' changes and single quotes should speed things up a bit.

**Comment by epacke** [comment]
Yeah, let's test it internally a while and see. Still struggling with REST on some of my machines. It's depressing how bad it is compared to the SOAP api. Joe Pruitt really ran a solid API team over at F5 back in the days, not sure what happened to REST. :)

**Pull request merged**
