### PR TITLE
Updating data-group list parsing to use the rest API

### PR DESCRIPTION
**Pull request by epacke**
An exception is thrown on some of our F5:s using 12.1.3. Adding a patch that seems to work for us. What do you think?

#152

### CODE REVIEW

**Comment by timriker** [comment]
Is the REST API available to read-only accounts now?
If so, it would sure be nice to get off the plugin and to REST for everything thereby making the powershell script portable. ie: running it on other than windows servers.
I hope to test this out today.

**Comment by epacke** [comment]
Hi
Yes, it's been for quite a while:
https://loadbalancing.se/2017/05/10/using-f5-rest-api-with-roles/

Main reason for keeping the plugin has been to support v10 and v11, but it starts to feel silly. Let's migrate the resources one by one so we can change the scope per PR quite small? Maybe something like this PR?

/Patrik

**Comment by timriker** [comment]
I think we should convert over to REST. Those with older boxen can use an admin account if they want to run the new version. I didn't merge this, I added some more verbose logging, and then found an error that was not handling null "values" in datagroups. I do think we should work towards a REST based version, but I'd like to see if the fix in my branch works for you first.

**Comment by epacke** [comment]
What do you mean by null values? Could you please give me a sample data group config that I can test with? Which version is it happening on?

**Comment by epacke** [comment]
@timriker Could you please elaborate what you meant? I'm keen to close this PR before it becomes bigger than it is.

**Comment by timriker** [comment]
I got an error loading an address datagroup that was empty. I added the try catch, and didn't see the error again. I've since tried without the try/catch and I can't get it to cause an error again.
Where are you seeing the error? I'd love to fix it, but I can't reproduce it. Is this new? In other words the current version does not get any errors? I've tried to reproduce this, but no luck. :(

**Comment by epacke** [comment]
The issue only happens with some load balancers and it's not new. I had to introduce the fix in this PR 
when I installed BigIPReport in May at the place I'm at right now.

The issue does not seem to be version specific and could just be the SOAP API throwing a fit. Either way I think it's a good idea to move away from SOAP. Do you mind adding the try/catch to this PR and merging if it works fine?

**Comment by timriker** [comment]
I'm not sure the try/catch did anything as I can't reproduce your issue. If we're moving to REST, we should move everything. The only downside would be that for pre-v13 BIG-IP boxen, the report would need a local admin account to use REST. Still workable for anyone with old machines, like us, but the cross platform move would be a Good Thing. I'll have to alter my user on our pre-v13 systems, but we are trying to remove those anyway.

**Comment by epacke** [comment]
You can run the REST API as an RO user on v12 too by using tokens. The code in this PR actually supports that. Not sure about the ASM stuff, but the LTM sure does.

**Comment by epacke** [comment]
Look here for more information:
https://loadbalancing.se/2017/05/10/using-f5-rest-api-with-roles/

**Pull request merged**
